version: 2.1
# Use a package of configuration called an orb.

jobs:
  configure_infrastructure: 
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
          - "59:98:8e:04:2a:4b:b1:b5:9c:fd:e5:46:d8:d3:fe:a1" # You can get this ID in the section where you registered the SSH Key
      

workflows:
  # Name the workflow "welcome"
  default:
    # Run the welcome/run job in its own container
    jobs:
      - configure_infrastructure
