version: 2.1
# Use a package of configuration called an orb.
#
jobs:
  configure_infrastructure: 
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["8d:e9:61:40:a4:5a:bb:20:be:f4:4e:6f:53:cf:d4:9d"] # You can get this ID in the section where you registered the SSH Key
      

workflows:
  # Name the workflow "welcome"
  default:
    # Run the welcome/run job in its own container
    jobs:
      - configure_infrastructure
